apiVersion: v1
kind: Service
metadata:
  name: k8s-hello-api
  labels:
    app: k8s-hello-api
spec:
  type: ClusterIP
  selector:
    app: k8s-hello-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP